language: android

android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by project
    - build-tools-21.1.2

    # The SDK version used to compile project
    - android-21

    # Additional components
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify system image, run emulators during tests
    - sys-img-armeabi-v7a-android-14
    - sys-img-x86-android-14